# Generated by Django 4.0.1 on 2022-04-25 12:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_description_alter_product_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=57)),
                ('email', models.EmailField(max_length=57)),
                ('subject', models.CharField(max_length=57)),
                ('information', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
