# Generated by Django 4.0.1 on 2022-04-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='information',
        ),
        migrations.AddField(
            model_name='contact',
            name='imformation',
            field=models.TextField(default='teteteteterterterte'),
        ),
    ]
